export const ADD_ORDER = "ADD_ORDER";
export const GET_ONE_ORDER = "GET_ONE_ORDER";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS"
export const GET_ALL_DRIVER_ORDERS = "GET_ALL_DRIVER_ORDERS"
export const GET_ALL_CLIENT_ORDERS = "GET_ALL_CLIENT_ORDERS"
export const GET_COORD_FROM="GET_COORD_FROM"
export const CHANGE_STATUS="CHANGE_STATUS"